blank_issues_enabled: true
contact_links:
  - name: Telestai Core Security Policy
    url: https://github.com/Telestai-Foundation/Telestai/blob/master/SECURITY.md
    about: View security policy
  - name: Telestai Core Developers
    url: https://telestaicore.org
    about: Telestai Core homepage
