#!/usr/bin/env bash
#
#  telestaid The telestai core server.
#
#
# chkconfig: 345 80 20
# description: telestaid
# processname: telestaid
#

# Source function library.
. /etc/init.d/functions

# you can override defaults in /etc/sysconfig/telestaid, see below
if [ -f /etc/sysconfig/telestaid ]; then
        . /etc/sysconfig/telestaid
fi

RETVAL=0

prog=telestaid
# you can override the lockfile via BITCOIND_LOCKFILE in /etc/sysconfig/telestaid
lockfile=${BITCOIND_LOCKFILE-/var/lock/subsys/telestaid}

# telestaid defaults to /usr/bin/telestaid, override with BITCOIND_BIN
telestaid=${BITCOIND_BIN-/usr/bin/telestaid}

# telestaid opts default to -disablewallet, override with BITCOIND_OPTS
telestaid_opts=${BITCOIND_OPTS--disablewallet}

start() {
    echo -n $"Starting $prog: "
    daemon $DAEMONOPTS $telestaid $telestaid_opts
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch $lockfile
    return $RETVAL
}

stop() {
    echo -n $"Stopping $prog: "
    killproc $prog -t600
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f $lockfile
    return $RETVAL
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status $prog
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: service $prog {start|stop|status|restart}"
        exit 1
        ;;
esac
